In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\yasir\Desktop\Data Analyst Coursework\Python\Python for Data Analysis\Pandas\Customer Call List.xlsx")

In [3]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
df=df.drop_duplicates()

In [5]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [6]:
del df['Not_Useful_Column']

In [7]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [8]:
df['Last_Name']=df['Last_Name'].str.strip('123._/')

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\120419933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name']=df['Last_Name'].str.strip('123._/')

In [9]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [10]:
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\4182724920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','', regex=True)

In [11]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x: str(x))

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\893764029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']=df['Phone_Number'].apply(lambda x: str(x))

In [12]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x: x[0:3]+ '-'+ x[3:6]+'-'+x[6:10])

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\1105521531.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']=df['Phone_Number'].apply(lambda x: x[0:3]+ '-'+ x[3:6]+'-'+x[6:10])

In [13]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [14]:
df['Phone_Number']=df['Phone_Number'].str.replace('nan--','', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\4088251720.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']=df['Phone_Number'].str.replace('nan--','', regex=True)

In [15]:
df['Phone_Number']=df['Phone_Number'].str.replace('Na--','', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\3661409147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']=df['Phone_Number'].str.replace('Na--','', regex=True)

In [16]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [17]:
df[['Street Address','State','Zip_Code']]=df['Address'].str.split(',',n=2,expand=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\1302641367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street Address','State','Zip_Code']]=df['Address'].str.split(',',n=2,expand=True)
C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\1302641367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street Address','State','Zip_Code']]=df['Address'].str.split(',',n=2,expand=True)
C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\1302641367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street Address','State','Zip_Code']]=df['Address'].str.split(',',n=2,expand=True)

In [18]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [19]:
del df['Address']

In [20]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [21]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\3877710085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y', regex=True)

In [22]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\3641852379.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N', regex=True)

In [23]:
df.fillna

<bound method NDFrame.fillna of     CustomerID First_Name   Last_Name  Phone_Number Paying Customer  \
0         1001      Frodo     Baggins  123-545-5421             Yes
1         1002       Abed       Nadir  123-643-9775              No
2         1003     Walter       White                             N
3         1004     Dwight     Schrute  123-543-2345             Yes
4         1005        Jon        Snow  876-678-3469               Y
5         1006        Ron     Swanson  304-762-2467             Yes
6         1007       Jeff      Winger                            No
7         1008   Sherlock      Holmes  876-678-3469               N
8         1009    Gandalf         NaN                           Yes
9         1010      Peter      Parker  123-545-5421             Yes
10        1011    Samwise      Gamgee                           Yes
11        1012      Harry      Potter                             Y
12        1013        Don      Draper  123-543-2345             Yes
13        1014     Leslie       Knope  876-678-3469             Yes
14        1015       Toby  Flenderson  304-762-2467               N
15        1016        Ron     Weasley  123-545-5421              No
16        1017   Michael        Scott  123-643-9775             Yes
17        1018      Clark        Kent                             Y
18        1019      Creed      Braton                           N/a
19        1020     Anakin   Skywalker  876-678-3469             Yes

   Do_Not_Contact        Street Address          State Zip_Code
0               N        123 Shire Lane          Shire     None
1               Y   93 West Main Street           None     None
2             NaN    298 Drugs Driveway           None     None
3               Y      980 Paper Avenue   Pennsylvania    18503
4               N      123 Dragons Road           None     None
5               Y      768 City Parkway           None     None
6               N     1209 South Street           None     None
7               N         98 Clue Drive           None     None
8             NaN      123 Middle Earth           None     None
9               N      25th Main Street       New York     None
10              N        612 Shire Lane          Shire     None
11            NaN  2394 Hogwarts Avenue           None     None
12              N      2039 Main Street           None     None
13              N      343 City Parkway           None     None
14              N         214 HR Avenue           None     None
15              N  2395 Hogwarts Avenue           None     None
16              N      121 Paper Avenue   Pennsylvania     None
17            NaN       3498 Super Lane           None     None
18              Y                   N/a           None     None
19              N     910 Tatooine Road       Tatooine     None  >

In [24]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [25]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\3154855446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y', regex=True)

In [26]:
df['Paying Customer']=df['Paying Customer'].str.replace('No','N', regex=True)

C:\Users\yasir\AppData\Local\Temp\ipykernel_6056\766702811.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Paying Customer']=df['Paying Customer'].str.replace('No','N', regex=True)

In [27]:
df=df.replace('N/a','')

In [28]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [29]:
df=df.fillna('')

In [30]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [31]:
for x in df.index:
    if df.loc[x,'Do_Not_Contact']=='Y':
        df.drop(x, inplace=True)

In [32]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [33]:
for x in df.index:
    if df.loc[x,"Phone_Number"] =='':
        df.drop(x,inplace=True)

In [36]:
df.reset_index(drop=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,